<?php

namespace Database\Seeders;

use App\Models\Events;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventsDailyNumbersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('tm_daily_numbers')->insert([
            'name' => fake()->name,
            'url' => fake()->url,
            'start_date' => fake()->dateTimeBetween('-30 days', '+30 days')->format('Y-m-d H:i:s'),
            'segment_id' => fake()->randomNumber(),
            'venue_name' => fake()->name,
            'venue_id' => fake()->randomNumber(),
            'tm_event_id' => Events::inRandomOrder()->first()->id,
            'statistic_date' => fake()->dateTimeBetween('-30 days', '+30 days')->format('Y-m-d H:i:s'),
            'gaprimary' => fake()->randomNumber(),
            'garesale' => fake()->randomNumber(),
            'gavip' => fake()->randomNumber(),
            'gaplatinum' => fake()->randomNumber(),
            'primary' => fake()->randomNumber(),
            'resale' => fake()->randomNumber(),
            'vip' => fake()->randomNumber(),
            'platinum' => fake()->randomNumber(),
            'total' => fake()->randomNumber(3),
            'yesterday_gaprimary' => fake()->randomNumber(),
            'yesterday_garesale' => fake()->randomNumber(),
            'yesterday_gavip' => fake()->randomNumber(),
            'yesterday_gaplatinum' => fake()->randomNumber(),
            'yesterday_primary' => fake()->randomNumber(),
            'yesterday_resale' => fake()->randomNumber(),
            'yesterday_vip' => fake()->randomNumber(),
            'yesterday_platinum' => fake()->randomNumber(),
            'yesterday_total' => fake()->randomNumber(3),
            'added_gaprimary' => fake()->randomNumber(),
            'added_garesale' => fake()->randomNumber(),
            'added_gavip' => fake()->randomNumber(),
            'added_gaplatinum' => fake()->randomNumber(),
            'added_primary' => fake()->randomNumber(),
            'added_resale' => fake()->randomNumber(),
            'added_vip' => fake()->randomNumber(),
            'added_platinum' => fake()->randomNumber(),
            'added_total' => fake()->randomNumber(3),
            'sold_gaprimary' => fake()->randomDigit(),
            'sold_garesale' => fake()->randomDigit(),
            'sold_gavip' => fake()->randomDigit(),
            'sold_gaplatinum' => fake()->randomDigit(),
            'sold_primary' => fake()->randomNumber(2),
            'sold_resale' => fake()->randomDigit(),
            'sold_vip' => fake()->randomDigit(),
            'sold_platinum' => fake()->randomDigit(),
            'sold_total' => fake()->randomNumber(2),
            'thirdparty' => fake()->randomNumber(),
            'yesterday_thirdparty' => fake()->randomNumber(),
            'added_thirdparty' => fake()->randomNumber(),
            'sold_thirdparty' => fake()->randomNumber(),
            'day_primary_delta' => fake()->randomNumber(),
            'day_primary_delta_diff' => fake()->randomNumber(),
            'week_primary_delta' => fake()->randomNumber(),
            'week_primary_delta_diff' => fake()->randomNumber(),
            'month_primary_delta' => fake()->randomNumber(),
            'month_primary_delta_diff' => fake()->randomNumber(),
            'day_gaprimary_delta' => fake()->randomNumber(),
            'day_gaprimary_delta_diff' => fake()->randomNumber(),
            'week_gaprimary_delta' => fake()->randomNumber(),
            'week_gaprimary_delta_diff' => fake()->randomNumber(),
            'month_gaprimary_delta' => fake()->randomNumber(),
            'month_gaprimary_delta_diff' => fake()->randomNumber(),
            'day_vip_delta' => fake()->randomNumber(),
            'day_vip_delta_diff' => fake()->randomNumber(),
            'week_vip_delta' => fake()->randomNumber(),
            'week_vip_delta_diff' => fake()->randomNumber(),
            'month_vip_delta' => fake()->randomNumber(),
            'month_vip_delta_diff' => fake()->randomNumber(),
            'day_platinum_delta' => fake()->randomNumber(),
            'day_platinum_delta_diff' => fake()->randomNumber(),
            'week_platinum_delta' => fake()->randomNumber(),
            'week_platinum_delta_diff' => fake()->randomNumber(),
            'month_platinum_delta' => fake()->randomNumber(),
            'month_platinum_delta_diff' => fake()->randomNumber(),
            'day_resale_delta' => fake()->randomNumber(),
            'day_resale_delta_diff' => fake()->randomNumber(),
            'week_resale_delta' => fake()->randomNumber(),
            'week_resale_delta_diff' => fake()->randomNumber(),
            'month_resale_delta' => fake()->randomNumber(),
            'month_resale_delta_diff' => fake()->randomNumber(),
            'day_garesale_delta' => fake()->randomNumber(),
            'day_garesale_delta_diff' => fake()->randomNumber(),
            'week_garesale_delta' => fake()->randomNumber(),
            'week_garesale_delta_diff' => fake()->randomNumber(),
            'month_garesale_delta' => fake()->randomNumber(),
            'month_garesale_delta_diff' => fake()->randomNumber(),
            'week_added_gaprimary' => fake()->randomNumber(),
            'month_added_gaprimary' => fake()->randomNumber(),
            'week_added_garesale' => fake()->randomNumber(),
            'month_added_garesale' => fake()->randomNumber(),
            'week_added_gavip' => fake()->randomNumber(),
            'month_added_gavip' => fake()->randomNumber(),
            'week_added_gaplatinum' => fake()->randomNumber(),
            'month_added_gaplatinum' => fake()->randomNumber(),
            'week_added_primary' => fake()->randomNumber(),
            'month_added_primary' => fake()->randomNumber(),
            'week_added_resale' => fake()->randomNumber(),
            'month_added_resale' => fake()->randomNumber(),
            'week_added_vip' => fake()->randomNumber(),
            'month_added_vip' => fake()->randomNumber(),
            'week_added_platinum' => fake()->randomNumber(),
            'month_added_platinum' => fake()->randomNumber(),
            'week_added_total' => fake()->randomNumber(),
            'month_added_total' => fake()->randomNumber(),
            'week_sold_gaprimary' => fake()->randomNumber(),
            'month_sold_gaprimary' => fake()->randomNumber(),
            'week_sold_garesale' => fake()->randomNumber(),
            'month_sold_garesale' => fake()->randomNumber(),
            'week_sold_gavip' => fake()->randomNumber(),
            'month_sold_gavip' => fake()->randomNumber(),
            'week_sold_gaplatinum' => fake()->randomNumber(),
            'month_sold_gaplatinum' => fake()->randomNumber(),
            'week_sold_primary' => fake()->randomNumber(),
            'month_sold_primary' => fake()->randomNumber(),
            'week_sold_resale' => fake()->randomNumber(),
            'month_sold_resale' => fake()->randomNumber(),
            'week_sold_vip' => fake()->randomNumber(),
            'month_sold_vip' => fake()->randomNumber(),
            'week_sold_platinum' => fake()->randomNumber(),
            'month_sold_platinum' => fake()->randomNumber(),
            'week_sold_total' => fake()->randomNumber(),
            'month_sold_total' => fake()->randomNumber(),
            'week_added_thirdparty' => fake()->randomNumber(),
            'month_added_thirdparty' => fake()->randomNumber(),
            'week_sold_thirdparty' => fake()->randomNumber(),
            'month_sold_thirdparty' => fake()->randomNumber(),
            'last_scrape' => fake()->dateTimeBetween('-30 days', '+30 days')->format('Y-m-d H:i:s'),
            'created_at' => fake()->dateTimeBetween('-30 days', '+30 days')->format('Y-m-d H:i:s'),
            'updated_at' => fake()->dateTimeBetween('-30 days', '+30 days')->format('Y-m-d H:i:s'),
        ]);

    }
}
